# Generated by Django 6.0.4 on 2026-08-25 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('model_used', models.CharField(default='gemini', max_length=100)),
                ('prompt_sent', models.TextField()),
                ('output', models.TextField(blank=True)),
                ('time_taken_ms', models.IntegerField(default=0)),
                ('token_count', models.IntegerField(default=0)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aida_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_number', models.IntegerField(default=1)),
                ('trigger', models.CharField(default='scheduler', max_length=100)),
                ('tasks_analyzed', models.IntegerField(default=0)),
                ('strategies_updated', models.IntegerField(default=0)),
                ('knowledge_added', models.IntegerField(default=0)),
                ('avg_score_before', models.FloatField(default=0.0)),
                ('avg_score_after', models.FloatField(default=0.0)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aida_improvement_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(default='general', max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('source', models.CharField(default='execution', max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('relevance_score', models.FloatField(default=1.0)),
                ('used_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aida_knowledge',
                'ordering': ['-relevance_score', '-used_count'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prompt_template', models.TextField()),
                ('domain', models.CharField(default='general', max_length=50)),
                ('conditions', models.JSONField(default=dict)),
                ('success_rate', models.FloatField(default=0.5)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aida_strategies',
                'ordering': ['-success_rate'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_request', models.TextField()),
                ('goal', models.TextField()),
                ('constraints', models.JSONField(default=list)),
                ('expected_output', models.TextField(blank=True)),
                ('difficulty', models.IntegerField(default=1)),
                ('domain', models.CharField(choices=[('code', 'Kod'), ('math', 'Matematika'), ('language', 'Til'), ('reasoning', 'Mantiq'), ('knowledge', 'Bilim'), ('creative', 'Ijodiy'), ('analysis', 'Tahlil'), ('general', 'Umumiy')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('running', 'Bajarilmoqda'), ('done', 'Tugallandi'), ('failed', 'Muvaffaqiyatsiz'), ('retrying', 'Qayta')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('source', models.CharField(default='user', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aida_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('clarity_score', models.FloatField(default=0.0)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('error_detected', models.BooleanField(default=False)),
                ('error_type', models.CharField(choices=[('none', 'Xato yoq'), ('logic', 'Mantiqiy'), ('factual', 'Faktik'), ('format', 'Format'), ('incomplete', 'Tolik emas'), ('irrelevant', 'Mavzudan tashqari'), ('hallucination', "Noto'g'ri")], default='none', max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('improved', models.BooleanField(default=False)),
                ('evaluator', models.CharField(default='auto', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='self_improvement.execution')),
            ],
            options={
                'db_table': 'aida_evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='self_improvement.strategy'),
        ),
        migrations.AddField(
            model_name='execution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='self_improvement.task'),
        ),
    ]
