"""Repository interfaces (ports) for the Domain layer.

These define contracts that Infrastructure must implement.
Domain depends on these interfaces, not on concrete implementations.
"""

from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any

from ..entities import (
    AgentSpec, AgentContext, AgentResult, AgentStatus,
    Message, Completion, ProviderSpec,
    ToolSpec, ToolResult,
    MemoryItem, MemoryQuery, MemoryType,
    Session, Project, WorkflowTemplate,
)


class AgentRepository(ABC):
    @abstractmethod
    async def register(self, spec: AgentSpec) -> None: ...
    @abstractmethod
    async def get(self, name: str) -> AgentSpec | None: ...
    @abstractmethod
    async def list(self) -> list[AgentSpec]: ...
    @abstractmethod
    async def execute(self, agent_name: str, ctx: AgentContext) -> AgentResult: ...
    @abstractmethod
    async def get_status(self, agent_name: str) -> AgentStatus: ...


class ToolRepository(ABC):
    @abstractmethod
    async def register(self, spec: ToolSpec, execute_fn: Any) -> None: ...
    @abstractmethod
    async def get(self, name: str) -> ToolSpec | None: ...
    @abstractmethod
    async def list(self) -> list[ToolSpec]: ...
    @abstractmethod
    async def execute(self, tool_name: str, **kwargs) -> ToolResult: ...


class ProviderRepository(ABC):
    @abstractmethod
    async def register(self, spec: ProviderSpec, chat_fn: Any, stream_fn: Any = None) -> None: ...
    @abstractmethod
    async def get(self, name: str) -> ProviderSpec | None: ...
    @abstractmethod
    async def list(self) -> list[ProviderSpec]: ...
    @abstractmethod
    async def chat(self, messages: list[Message], provider: str = "", **kwargs) -> Completion: ...
    @abstractmethod
    async def chat_stream(self, messages: list[Message], provider: str = "", **kwargs): ...
    @abstractmethod
    async def check_health(self, provider: str = "") -> bool: ...


class MemoryRepository(ABC):
    @abstractmethod
    async def store(self, item: MemoryItem) -> str: ...
    @abstractmethod
    async def get(self, memory_id: str) -> MemoryItem | None: ...
    @abstractmethod
    async def search(self, query: MemoryQuery) -> list[MemoryItem]: ...
    @abstractmethod
    async def update(self, item: MemoryItem) -> bool: ...
    @abstractmethod
    async def delete(self, memory_id: str) -> bool: ...
    @abstractmethod
    async def count(self, memory_type: MemoryType | None = None) -> int: ...
    @abstractmethod
    async def clear(self, memory_type: MemoryType | None = None) -> int: ...
    @abstractmethod
    async def get_stats(self) -> dict: ...


class SessionRepository(ABC):
    @abstractmethod
    async def create(self, session: Session) -> str: ...
    @abstractmethod
    async def get(self, session_id: str) -> Session | None: ...
    @abstractmethod
    async def list(self, limit: int = 50, offset: int = 0) -> list[Session]: ...
    @abstractmethod
    async def update(self, session: Session) -> bool: ...
    @abstractmethod
    async def delete(self, session_id: str) -> bool: ...
    @abstractmethod
    async def add_message(self, session_id: str, message: dict) -> bool: ...
    @abstractmethod
    async def get_messages(self, session_id: str, limit: int = 100) -> list[dict]: ...


class ProjectRepository(ABC):
    @abstractmethod
    async def open(self, path: str) -> Project: ...
    @abstractmethod
    async def close(self, project_id: str) -> bool: ...
    @abstractmethod
    async def get(self, project_id: str) -> Project | None: ...
    @abstractmethod
    async def list(self) -> list[Project]: ...
    @abstractmethod
    async def get_files(self, project_id: str) -> list[dict]: ...
    @abstractmethod
    async def read_file(self, project_id: str, file_path: str) -> str: ...
    @abstractmethod
    async def write_file(self, project_id: str, file_path: str, content: str) -> bool: ...


class CodebaseRepository(ABC):
    @abstractmethod
    async def index_file(self, file_path: str) -> dict: ...
    @abstractmethod
    async def index_project(self, project_path: str) -> dict: ...
    @abstractmethod
    async def search(self, query: str, language: str = "") -> list[dict]: ...
    @abstractmethod
    async def get_symbol(self, symbol_name: str, file_path: str = "") -> list[dict]: ...
    @abstractmethod
    async def get_dependencies(self, file_path: str) -> list[str]: ...


class MetricsRepository(ABC):
    @abstractmethod
    async def record_request(self, endpoint: str, method: str, status: int, latency_ms: int, **kwargs) -> None: ...
    @abstractmethod
    async def record_agent_call(self, agent: str, task: str, success: bool, latency_ms: int, **kwargs) -> None: ...
    @abstractmethod
    async def get_stats(self, hours: int = 24) -> dict: ...
    @abstractmethod
    async def get_agent_stats(self, hours: int = 24) -> list[dict]: ...
    @abstractmethod
    async def get_health_score(self) -> float: ...


class KnowledgeRepository(ABC):
    @abstractmethod
    async def add(self, content: str, tags: list[str] = None, source: str = "") -> str: ...
    @abstractmethod
    async def search(self, query: str, limit: int = 10) -> list[dict]: ...
    @abstractmethod
    async def get(self, knowledge_id: str) -> dict | None: ...
    @abstractmethod
    async def delete(self, knowledge_id: str) -> bool: ...
    @abstractmethod
    async def get_stats(self) -> dict: ...


class WorkflowRepository(ABC):
    @abstractmethod
    async def register_template(self, template: WorkflowTemplate) -> None: ...
    @abstractmethod
    async def get_template(self, name: str) -> WorkflowTemplate | None: ...
    @abstractmethod
    async def list_templates(self) -> list[WorkflowTemplate]: ...
    @abstractmethod
    async def execute(self, template_name: str, context: dict) -> Any: ...
