from django.urls import path, re_path

from .views import (
    api_architecture_analyze,
    api_chat,
    api_chat_stream,
    api_code_analyze,
    api_code_fix,
    api_code_generate,
    api_code_improve,
    api_code_optimize,
    api_code_preview,
    api_code_review,
    api_code_tests,
    api_debug_assist,
    api_docker_generate,
    api_feedback_analytics,
    api_feedback_analyze,
    api_feedback_submit,
    api_framework_generate,
    api_keys_create,
    api_keys_list,
    api_knowledge_suggest,
    api_kubernetes_generate,
    api_language_generate,
    api_manager_get,
    api_manager_list,
    api_manager_load,
    api_manager_pull,
    api_manager_remove,
    api_manager_select,
    api_manager_unload,
    api_models_discover,
    api_performance_tuning,
    api_platform_chat,
    api_project_close,
    api_project_current,
    api_project_git_clone,
    api_project_list,
    api_project_open,
    api_runtime_delete,
    api_runtime_files,
    api_runtime_read,
    api_runtime_run,
    api_runtime_save,
    api_runtime_server_output,
    api_runtime_server_start,
    api_runtime_server_stop,
    api_session_create,
    api_session_history,
    api_sessions_list,
    api_status,
    api_training_analyze,
    api_training_domain,
    api_training_save,
    api_training_stats,
    api_version_control,
    code_workspace,
    code_workspace_asset,
    dist_asset,
    login_page,
    spa_index,
)

from .model_management_views import (
    api_models_status,
    api_models_start,
    api_models_stop,
    api_models_switch,
    api_models_list,
    api_models_install,
    api_models_pull,
)

from .model_views import (
    model_discover,
    manager_list,
    manager_get,
    manager_pull,
    manager_remove,
    manager_load,
    manager_unload,
    manager_select,
)


urlpatterns = [
    re_path(r"^assets/(?P<asset_path>.+)$", dist_asset, name="dist-asset"),
    path("api/keys/", api_keys_list, name="api-keys-list"),
    path("api/keys/create/", api_keys_create, name="api-keys-create"),
    path("api/status/", api_status, name="api-status"),
    path("api/chat/", api_chat, name="api-chat"),
    path("api/chat/stream/", api_chat_stream, name="api-chat-stream"),
    path("api/sessions/", api_sessions_list, name="api-sessions-list"),
    path("api/sessions/create/", api_session_create, name="api-session-create"),
    path("api/sessions/<str:session_id>/history/", api_session_history, name="api-session-history"),
    path("api/platform/chat/", api_platform_chat, name="api-platform-chat"),
    path("api/code/generate/", api_code_generate, name="api-code-generate"),
    path("api/code/analyze/", api_code_analyze, name="api-code-analyze"),
    path("api/code/preview/", api_code_preview, name="api-code-preview"),
    path("api/code/fix/", api_code_fix, name="api-code-fix"),
    path("api/code/optimize/", api_code_optimize, name="api-code-optimize"),
    path("api/code/tests/", api_code_tests, name="api-code-tests"),
    path("api/code/improve/", api_code_improve, name="api-code-improve"),
    path("api/code/review/", api_code_review, name="api-code-review"),
    path("api/debug/assist/", api_debug_assist, name="api-debug-assist"),
    path("api/architecture/analyze/", api_architecture_analyze, name="api-architecture-analyze"),
    path("api/language/generate/", api_language_generate, name="api-language-generate"),
    path("api/framework/generate/", api_framework_generate, name="api-framework-generate"),
    path("api/version-control/", api_version_control, name="api-version-control"),
    path("api/docker/generate/", api_docker_generate, name="api-docker-generate"),
    path("api/kubernetes/generate/", api_kubernetes_generate, name="api-kubernetes-generate"),
    path("api/performance/tuning/", api_performance_tuning, name="api-performance-tuning"),
    path("api/feedback/submit/", api_feedback_submit, name="api-feedback-submit"),
    path("api/feedback/analytics/", api_feedback_analytics, name="api-feedback-analytics"),
    path("api/feedback/analyze/", api_feedback_analyze, name="api-feedback-analyze"),
    path("api/training/save/", api_training_save, name="api-training-save"),
    path("api/training/domain/", api_training_domain, name="api-training-domain"),
    path("api/training/stats/", api_training_stats, name="api-training-stats"),
    path("api/training/analyze/", api_training_analyze, name="api-training-analyze"),
    path("api/knowledge/suggest/", api_knowledge_suggest, name="api-knowledge-suggest"),
    path("api/models/discover/", api_models_discover, name="api-models-discover"),
    path("api/manager/list/", api_manager_list, name="api-manager-list"),
    path("api/manager/get/<str:model_id>/", api_manager_get, name="api-manager-get"),
    path("api/manager/pull/", api_manager_pull, name="api-manager-pull"),
    path("api/manager/remove/", api_manager_remove, name="api-manager-remove"),
    path("api/manager/load/", api_manager_load, name="api-manager-load"),
    path("api/manager/unload/", api_manager_unload, name="api-manager-unload"),
    path("api/manager/select/", api_manager_select, name="api-manager-select"),
    path("api/runtime/save/", api_runtime_save, name="api-runtime-save"),
    path("api/runtime/read/", api_runtime_read, name="api-runtime-read"),
    path("api/runtime/delete/", api_runtime_delete, name="api-runtime-delete"),
    path("api/runtime/files/", api_runtime_files, name="api-runtime-files"),
    path("api/runtime/run/", api_runtime_run, name="api-runtime-run"),
    path("api/runtime/server/start/", api_runtime_server_start, name="api-runtime-server-start"),
    path("api/runtime/server/stop/", api_runtime_server_stop, name="api-runtime-server-stop"),
    path("api/runtime/server/output/", api_runtime_server_output, name="api-runtime-server-output"),
    path("api/project/open/", api_project_open, name="api-project-open"),
    path("api/project/close/", api_project_close, name="api-project-close"),
    path("api/project/current/", api_project_current, name="api-project-current"),
    path("api/project/list/", api_project_list, name="api-project-list"),
    path("api/project/git-clone/", api_project_git_clone, name="api-project-git-clone"),
    path("api/models/status/", api_models_status, name="api-models-status"),
    path("api/models/start/<str:provider_name>/", api_models_start, name="api-models-start"),
    path("api/models/stop/<str:provider_name>/", api_models_stop, name="api-models-stop"),
    path("api/models/switch/<str:provider_name>/", api_models_switch, name="api-models-switch"),
    path("api/models/list/", api_models_list, name="api-models-list"),
    path("api/models/install/<str:provider_name>/", api_models_install, name="api-models-install"),
    path("api/models/pull/", api_models_pull, name="api-models-pull"),
    # Consolidated model management API (model_views.py)
    path("api/models/discover/", model_discover, name="model-discover"),
    path("api/models/manage/list/", manager_list, name="manager-list"),
    path("api/models/manage/get/<str:model_id>/", manager_get, name="manager-get"),
    path("api/models/manage/pull/", manager_pull, name="manager-pull"),
    path("api/models/manage/remove/", manager_remove, name="manager-remove"),
    path("api/models/manage/load/", manager_load, name="manager-load"),
    path("api/models/manage/unload/", manager_unload, name="manager-unload"),
    path("api/models/manage/select/", manager_select, name="manager-select"),
    path("code/", code_workspace, name="code-workspace"),
    path("code_workspace/<path:file_path>", code_workspace_asset, name="code-workspace-asset"),
    path("login/", login_page, name="login-page-alt"),
    path("app/", spa_index, name="spa-index"),
    path("", login_page, name="login-page"),
]
